server:
  port: 6651  # 应用运行端口 若占用可修改

deepvision:
  tenant-id: zyxx
  ak: 7a04e90ad5e14b53
  sk: b53a4eb44e2c42d98b0fbda93086337d
#  api-base-url: http://10.250.186.247:20201/ds/api/v2/external  # 深瞳接口真实路径
  api-base-url: http://127.0.0.1:20201/ds/api/v2/external  # 测试路径
  knowledge-base-max-files: 10  # 知识库最大文件数（可配置）
  file-scan:
    dir: /data/shentong/   # 需要扫描的文件目录
    backup-dir: /data/backup/shentong/ # 备份目录
    cron: 0/10 * * * * ?         # 每30s执行一次文件扫描上传操作
    clean-days: 7               # 备份文件保留天数
  log:
    dir: /data/logs/   # 日志目录，应用的运行日志