server:
  port: 6651  # 应用运行端口 若占用可修改

deepvision:
  tenant-id: zyxx
  api-key: api_key_test
  secret: multibot@@zhiwei
  ak: 7a04e90ad5e14b53
  sk: b53a4eb44e2c42d98b0fbda93086337d
  user-id: dwwenjie_1
  workspace: team
  workspace-id: team_zyxx_dwwenjie_1_1750402391551
  api-base-url: http://10.250.186.247:20201/ds/api/v2/external  # 深瞳接口真实路径
  #api-base-url: http://127.0.0.1:20201/ds/api/v2/external  # 测试路径
  knowledge-base-max-files: 10  # 知识库最大文件数（可配置）
  file-scan:
    dir: /Users/shaoxiumin/shentongScan/   # 需要扫描的文件目录
    backup-dir: /Users/shaoxiumin/shentong/backup/ # 备份目录
    output-dir: /Users/shaoxiumin/shentong/merge/ # 合并文件输出路径
    cache-dir: /Users/shaoxiumin/shentong/cache/ # 合并文件输出路径
    cache-on: false # 合并文件输出路径
    cron: 0/10 * * * * ?         # 每30s执行一次文件扫描上传操作
    clean-days: 7               # 备份文件保留天数
    supported-extensions: "docx,doc,txt" # 支持的文件扩展名（可配置）

  log:
    dir: /Users/shaoxiumin/workspace/logs/shentong   # 日志目录，应用的运行日志